version: '3.8'

networks:
  default:

services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  backend-app:
    container_name: backend-app
    depends_on:
      - mysql-db
    build: ./backend-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $BACKEND_APP_LOCAL_PORT:$BACKEND_APP_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend-app:/app
      - /app/node_modules
    networks:
      - default

  frontend-app:
    container_name: frontend-app
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $FRONTEND_APP_LOCAL_PORT:$FRONTEND_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default

volumes: 
  mysql-volume: